### ISSUE TITLE
about Pros and Cons of Disruptor

### ISSUE THREAD

**Issue by HelloTo4x** [1399852153/MyDisruptor#1]
Hi, can u tell me what is Pros and Cons of Disruptor in the real world, especially in this project ? thank u so much

**Comment by 1399852153** [comment]
advantage：The biggest advantage of disruptor is very fast, disruptor is faster than popular memory queues including JUC ArrayBlockingQueue. For example, a data synchronization middleware “Alibaba Canal” uses disruptor.

defect：disruptor is difficult to learn and use. The easy-to-use JUC ArrayBlockingQueue is enough for most scenes.

My english is not very good, so the answer is a little simple. hope to help you.

**Comment by HelloTo4x** [comment]
thank u so much

**Comment by HelloTo4x** [comment]
do you know why it faster than ArrayBlockingQueue ?

**Comment by 1399852153** [comment]
ArrayBlockingQueue has some detect：
1. cpu cache false sharing problem
2. shared variables such as team head and tail references with too many Contention
3. queue elements generate a large amount of garbage when entering or leaving the queue
For more detailed answers, please refer to the official documents of lmax-disruptor：https://lmax-exchange.github.io/disruptor/disruptor.html.
if you understand Chinese，you can also refer to my blog：https://www.cnblogs.com/xiaoxiongcanguan/p/16318972.html

**Comment by HelloTo4x** [comment]
thank u so much
